### ISSUE TITLE
Revamp the price addition workflow

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#1085]
### Story

After some extensive scanning with Justin this weekend, I'm thinking of many small changes to apply to the main "proof+price(s) addition" workflow

### Todo

- [x] when adding a new price, automatically scroll down to the form: https://github.com/openfoodfacts/open-prices-frontend/pull/1072
- [x] right-align submit buttons: https://github.com/openfoodfacts/open-prices-frontend/pull/1068
- [ ] image upload: allow drag-and-drop: https://github.com/openfoodfacts/open-prices-frontend/issues/1084
- [ ] Price: move discount next to label
- [ ] Product: seperate product type & details ? move type next to label ? 
- [ ] required fields: turn the * from red to green when the field is valid ?
- [ ] Proof image: hide the "Select a proof" line
- [ ] Proof location: hide the "Select a location" line
- [ ] ...

### Related issues

- https://github.com/openfoodfacts/open-prices-frontend/issues/930
- https://github.com/openfoodfacts/open-prices-frontend/issues/974

**Comment by thibaultmol** [comment]
Another thing I was thinking of: I actually would love to be able to upload proofs at once. just dump them all in so I no longer need to worry about those files on my pc/phone.

In the current flow I have to remember which images i've already uploaded and which I haven't. to the point where i just open multiple tabs and upload all the images. so that I don't have to worry about it.

**Comment by serpico** [comment]
did you try https://prices.openfoodfacts.org/proofs/add/multiple ? ( it's in the side menu > Experiments > Add multiple proofs )

**Comment by raphodn** [comment]
@serpico ok so you're not going to be happy with the layout i guess ^^
- it's only half done (i need to take some time for the "normal" form fields)
- and think of an expert mode to save some clicks (i know, the new UI adds some clicks, I tried it quite a bit this weekend)

**Comment by thibaultmol** [comment]
I like the change of 'find the product' instead of whatever barcode it was before. 
i really like how the barcode is already prefilled in the 'type the barcode' field, not sure if that was the case before

one thing i would like to ask: could we have the cropped image of the product, very large, above the 'type the barcode' field.
![Image](https://github.com/user-attachments/assets/47c5feed-6eb5-4bd5-8d77-7e0d8945f868)

right above this i would like to see the price time image massive, so i can easily read it.

Another thing it'd like to ask: since EAN13 has a builtin checksum. is it possible to re-run the ocr a second or third time slightly differently somehow, until it finds a correct barcode OR it hits 3 tries?

**Comment by thibaultmol** [comment]
also, i know this will increase the amount of api calls maybe. but having it automatically check the api for products anytime it matches a common barcode char amount like 13. it shows that it found a product inside the 'type a barcode' screen. without having to submit it. so i can see if i typed it correct before having to close the window

**Comment by serpico** [comment]
> [@serpico](https://github.com/serpico) ok so you're not going to be happy with the new layout i guess ^^
> 
>     * it's only half done (i need to take some time for the "normal" form fields)
> 
>     * and we can think of an expert mode to save some clicks (i know, the new UI adds some clicks, I tried it quite a bit this weekend)

Don't worry, try away

**Comment by raphodn** [comment]
thanks for the feedback @thibaultmol ! indeed i share your following points :
a. the "type a barcode" could display the image above (or below) ; note that it's used elsewhere like the "Multiple add price" so it will have the full proof image, not just the cropped one.
b. an intermediate "validation" step could be nice, so that you stay on the modal until you've find the correct barcode 👌 
c. the EAN check result could also be displayed somewhere (it is already display on the "product card", if b. is done then it'll come with it

**Comment by raphodn** [comment]
2 new changes on the barcode scanner : 
- I added a result feedback for the "type" mode, the result is displayed below, and the user simply needs to click on the product card to confirm : https://github.com/openfoodfacts/open-prices-frontend/pull/1108
- I also added a new settings, to change the default tab. So that on your laptop you can set it to "type" and save a click 😍 : https://github.com/openfoodfacts/open-prices-frontend/pull/1111 (soon to be deployed)

**Comment by raphodn** [comment]
New screenshots after some additional changes

|proof type|Step 1: proof|Step 2: price(s)|
|---|---|---|
|receipt|![Image](https://github.com/user-attachments/assets/41aa6623-7cbd-4119-8f91-2e01821188e9)|![Image](https://github.com/user-attachments/assets/942bad1c-694d-4d3d-ae4d-92d8f199126c)|

**Comment by raphodn** [comment]
extra todo following feedback:
- Location finder: show a (dismissable) message informing users they can set the default tab in the settings
- Barcode scanner: show a (dismissable) message informing users they can set the default tab in the settings
- Barocde scanner > type: find a way to allow users to skip the validation step
- allow translation of the "Organic" checkbox (category label). add new labels ?
- after the barcode scanner, when the product is selected, if the price is still empty, focus directly on the field

**Comment by raphodn** [comment]
@TTalex following feedback that for some fields (especially the "currency" where you need to go to your settings to change them) we would need to add a Help icon or link/popup, I've been thinking of changing the look and feel of our input fields..
- one option is what I've started in this PR - https://github.com/openfoodfacts/open-prices-frontend/pull/1329 - put back the label above, have an outline, makes it a bit similar to the buttons above, and allows to define a border green/red. will also allow to put a dedicated help
- another option (can be complementary) is to have a ❓ icon in the top right of the card, with a dialog explaining in more details how to upload

**Comment by TTalex** [comment]
For the specific case of currency, maybe the solution is in the drop-down. Add a "more" option to display all available currencies, and upon user selection add the currency to favorites.
Because even with a tutorial / good explanation, I find it a bit odd to have to go to settings for this.

**Comment by raphodn** [comment]
The "best" solution would be an onboarding page to select your language, country & currency

**Comment by raphodn** [comment]
Recent changes:
- replace v-checkbox with v-switch + add green color if True: #1437, #1438
- changed the look & feel of inputs (outline, label on top, green if filled & required): #1329, #1441, #1444
- added a red asterisk next to required field's labels: #1443

**Comment by raphodn** [comment]
I'm still frustrated with our current price/proof/validation forms
- some take too much height space
- too many different types of buttons and size
- not completely clear which actions are remaining

Looking at Vinted just now kinda gave me an epiphany to have full-width boxes + edit icons in the top right 👀 
(I'm not 100% of fan of their UI nevertheless, it's not clear which actions are remaining)

<img width="1403" height="971" alt="Image" src="https://github.com/user-attachments/assets/a52e23ca-e013-4e81-890e-ceada31e836a" />

cc @julia-gx
