### ISSUE TITLE
New page that lists all the proofs (by most recently uploaded first)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#1120]
### Story

We already have a list of latest prices. And lists of top products, locations & users.

Following a change in the backend - https://github.com/openfoodfacts/open-prices/pull/606 - users can request any proof from any user (it's open data after all).

So we're free to display all proofs to all users. This will help for transparency. Also for moderation once we have some!

### Todo

- [x] new /proofs page
- [x] show in the drawer
- [x] filtering ? ordering ?
- [x] allow clicking on footer chips
- [x] show compressed images
