### ISSUE TITLE
Gamification

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#137]
### Story

Make improvements to the app to nudge contributors to add more prices :)
- number of products "unlocked" (user added the product's first price)
- when scanning a product, message if there is no known price yet
- mayor of a location
- ?

**Comment by raphodn** [comment]
Created a discussion here : https://github.com/openfoodfacts/open-prices/discussions/399

**Comment by raphodn** [comment]
Following backend work: https://github.com/openfoodfacts/open-prices/issues/1362

### Todo

- [x] badge card
- [x] `/badges` list page with all the available badges: #2258
- [x] `/badges/:id` detail page with badge info + users: #2286
- [x] `/users/:id/badges` list page with all of the user's badges: #2262 
- [x] UserCard: badge_count chip: #2259
- [x] Stats: badge_count stat: #2260
- [ ] `/dashboard/badges`: similar to `/users/:id/badges` but also displays the greyed out ones with extra stats ?

### Demo

- https://prices.openfoodfacts.org/badges
- https://prices.openfoodfacts.org/users
- https://prices.openfoodfacts.org/stats
