### ISSUE TITLE
Basic search (by product barcode or category)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#167]
### Story

It's currently not easy to find a specific product or brand.

We could add a search box, by name / code / category name / brand / ...

### Tasks

- [x] search by code
- [x] search by category
- [ ] search by brand

**Comment by raphodn** [comment]
We could use the search-a-licious project : 
- https://github.com/openfoodfacts/search-a-licious
- https://search.openfoodfacts.org

**Comment by raphodn** [comment]
Backend issue : https://github.com/openfoodfacts/open-prices/issues/414
