### ISSUE TITLE
Price form: manage different currencies

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#35]
### Story

Currently only EUR is suggested.

We should store the full list of available currencies, with a simple typeahead search (on name or code or logo)

### Ideas

- use location to determine currency
- store currency to be reused (won't change often...)

### TODO

- [x] full list of currencies
- [x] replace search with typeahead
- [x] store last currency used
- [ ] display currency name depending on the user locale
