### ISSUE TITLE
Kill the permanent landing page, and turn it into a one time thing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#364]
### Problem

- Kill the permanent landing page, and turn it into a one time thing
- prices.openfoodfacts.org will be the app
- prices.openfoodfacts.org/about will be the existing landing page
- We have the promo in the app to read the landing page.

### Todo

- [x] new /about page with the existing content: #874
- [x] translate the page via Crowdin using the existing /fr page: #884
- [x] add to the drawer
- [x] change the link in the footer: https://github.com/openfoodfacts/open-prices-frontend/commit/e734a5f22186c5b1fb84bc44dae2d6bebba02f56
- [ ] serve the frontend app directly prices.openfoodfacts.org : https://github.com/openfoodfacts/open-prices/issues/482
- [x] final frontend config: #906
- [x] redirect any incoming traffic to /app (by removing the prefix): #882

**Comment by raphodn** [comment]
I'm going to take some inspiration from https://hunger.openfoodfacts.org :)
