### ISSUE TITLE
Better display products coming from non-OFF source

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#502]
### Story

Thanks to https://github.com/openfoodfacts/open-prices/issues/114 we are now getting products from OBF, OPFF & OPF.

We need to tell users from which source each product is coming from.

### Tasks

- [x] show the 4 sources in the footer
- [x] change the target urls depending on the product source
- [x] add a new product filter by source
- [x] if the product is not found, add a dropdown to let the user choose which source
