### ISSUE TITLE
Only require "Load more" button to be clicked once when viewing results (infinite scroll)

### ISSUE THREAD

**Issue by odin-h** [openfoodfacts/open-prices-frontend#529]
### Problem

The load more button is required to be clicked every time you want to load a new set of results when scrolling down the page. This can feel tedious when you want to load a lot of results.

### Proposed solution

After the user has clicked the "Load more" button once and indicated they want to continue loading more results, hide the button and load new results automatically next time the user scrolls down to near the bottom of the page.

### Todo

- [x] basic infinite scroll on the "top x" pages : #832, #833
- [ ] replace it everywhere
- [ ] improve the behavior (for now it starts loading the rest after scrolling 90% of the page. will have a slightly different behavior if the page has 10 elements or 100 elements loaded)

### Part of
- #88

**Comment by raphodn** [comment]
Hi @odin-h, thanks for the idea.

This requires to detect that the user is at (or close to) the bottom of the list.

I see that Vuetify has an "infinite scroll" module, maybe a good option : https://vuetifyjs.com/en/components/infinite-scroller/#usage

**Comment by raphodn** [comment]
Ok I deployed 2 PRs that replace these "load more" buttons with infinite scroll. On the "top X" pages.

The next step is to : 
- replace it everywhere
-  improve the behavior (for now it starts loading the rest after scrolling 90% of the page. will have a slightly different behavior if the page has 10 elements or 100 elements loaded)
