### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#585]
### Story

Add linting with [ESLint](https://eslint.org/docs/latest/use/getting-started)

### Todo

- [x] setup eslint
- [x] run eslint on all files
- [x] run eslint on commit (pre-commit config with husky & lint-staged)
- [ ] eslint plugin : prettier
- [ ] eslint plugin : cypress

#### Default

```
yarn add -D eslint
```

#### Plugin for Vue

https://eslint.vuejs.org/user-guide/

```
yarn add -D eslint-plugin-vue
```

#### Plugin for prettier

https://github.com/prettier/eslint-plugin-prettier

```
yarn add -D eslint-plugin-prettier eslint-config-prettier
```

#### Plugin for cypress

https://github.com/cypress-io/eslint-plugin-cypress/blob/master/FLAT-CONFIG.md

```

```

#### Pre-commit

With husky & lint-staged
- https://typicode.github.io/husky/how-to.html#manual-setup
- https://github.com/lint-staged/lint-staged
- add `--max-warnings=0` to have lint-staged stop on eslint warnings

Why not with [pre-commit](https://pre-commit.com/) ? Requires to install a python package...
```
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.3.0
    hooks:
    - id: eslint
      types: [javascript]

```
