### ISSUE TITLE
Papercut tracker

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/open-prices-frontend#65]
### What

```[tasklist]
### Papercuts
- [x] The take a picture button should be the Camera plus material icon
- [x] Turn Last prices into Latest prices
- [x] You should be able to click on "Open Prices" to come back to the home page
- [ ] The user menu has a logout icon if you're not logged in
- [ ] You should be able to click on the map popup to select a store
- [x] Can we add the time on the Latest prices to make it more exciting
- [ ] Add a "Top price per kilo page"
- [ ] Define a target basket on which to focus efforts
- [x] Add a "Add a new price" to the product page
- [ ] https://github.com/openfoodfacts/open-prices-frontend/issues/318
- [ ] In Stats, for whimsical effect, add: Max price (for the whole db), Min Price (for the whole db), Number of cities with at least a price, Number of countries with at least a price, Number of different stores with at least a price.
- [ ] Add a timeline view on the product page for a given store (with a store selector, and an option to add a new pricepoint for that specific product and that specific store)
- [ ] Allow to store favorite stores
- [ ] Allow people to become the "Mayor" of stores
- [ ] Attempt to detect location (and store), timestamp from EXIF metadata, and to attempt extracting barcodes from image
- [ ] Allow to change language
- [ ] Allow to force language in the URL scheme
- [ ] Allow prepopulation of the form in the URL Scheme (barcode, store, currency, date)
- [ ] Use Wikidata to get a photo of products without barcodes using their category
- [ ] https://github.com/openfoodfacts/open-prices-frontend/issues/100
- [ ] Create a worldwide real-time map of prices being added
- [ ] Create a worldwide map of stores with at least a price
- [ ] https://github.com/openfoodfacts/open-prices-frontend/issues/274
- [ ] Add a shortcut to promote the Hunger Games quantity game: https://hunger.openfoodfacts.org/questions?type=product_weight
- [ ] https://github.com/openfoodfacts/open-prices-frontend/issues/447
- [ ] Add links to Top Products, Top Locations, Top Users from the Stats page
```

**Comment by psankhe28** [comment]
@teolemon I'm interested in contributing to the implementation of a dark mode for this project. May I proceed with this task? Additionally, are we considering a specific color theme for the dark mode, or should I stick to a classic white and black scheme?

**Comment by raphodn** [comment]
@psankhe28 I created the issue, go ahead ! maybe something classic/basic to start with, and we'll improve it in future iterations :)

**Comment by psankhe28** [comment]
Okay

**Comment by raphodn** [comment]
Closing as this is not up to date anymore
