### ISSUE TITLE
Move some buttons (Add price, Share) to action menus

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#710]
### Story

Try to gain some vertical space by moving some buttons to action menus

### Todo

- [x] Product detail --> Product card
- [x] Product (category) detail & Category detail --> Category card
- [x] Location detail --> Location card
- [x] Proof detail --> Proof card
- [x] User detail --> User card
- [x] Brand detail --> Brand card
- [x] Date detail --> Date card

**Comment by raphodn** [comment]
last one merged ! https://github.com/openfoodfacts/open-prices-frontend/pull/715
