### ISSUE TITLE
Privacy : show price owner only on the price detail page

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#804]
### Story

Thanks to #795 we have a new page where we could display _metadata_ below the Price Card, with info like
- the price addition date
- the price owner
- the price edit history (one day ?)

This would allow : 
- to gain some px space in the Price Card
- hide the price owner and be a bit more privacy-concerned

### Todo

- [x] Price detail page : see issue #795
- [x] Price card: remove price owner : #806
- [ ] Proof detail page history section ?
- [x] Proof card: remove proof owner : #959
