### ISSUE TITLE
Revamp the landing page

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#843]
### Story

Linked with #364 (make the root of the app https://prices.openfoodfacts.org/ instead of https://prices.openfoodfacts.org/app/ )

### Currently

(logged-in user)

![Screenshot from 2024-09-28 15-29-37](https://github.com/user-attachments/assets/489aa066-16bc-48f1-914e-bf6239a94ef6)

### Todo

- [x] move actions (the 3 existing card-buttons) to the header & side drawer
- [x] show some global stats at the top
- [ ] show some personal stats below
- [x] show latest prices (25, but reduce to 5 on small screens)
- [ ] links to about, ...
- [ ] some info about OFF ?
- [x] reduce the footer height : https://github.com/openfoodfacts/open-prices-frontend/commit/6d0536748591f1264e8872b10831d73e46589c0c

get inspiration from https://hunger.openfoodfacts.org for instance !

**Comment by raphodn** [comment]
@serpico any feedback on the upcoming/new home page ?
https://prices.openfoodfacts.net/app/

**Comment by serpico** [comment]
Maybe it's just an impression but on some pages the "cards" look too big ( but maybe there's a reason, like more space for upcoming data displayed on them ), like in https://prices.openfoodfacts.org/app/prices, much fewer cards for the same screen size compare to previously but it's not on the .net so it must be from before...however I have all the extra chip (3) enabled ( but I had that before, since they're available ) and I have small screen laptop 12.5" so it's  only 6 and half cards before it felt like 9 or more. But it's probably just a matter of getting used to it.

**Comment by raphodn** [comment]
I share your feeling that the price cards size can be reduced, and the spacing between them as well 👌

**Comment by raphodn** [comment]
v2 deployed (there still room for improvement :)

![image](https://github.com/user-attachments/assets/3241d1d4-efa5-41c0-bf09-3eaace9496a3)
