### ISSUE TITLE
Move (all ?) the settings outside of the User dashboard

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#948]
### Story

Most (if not all) of the settings are display-related, and are stored in the cookies.
- they could also be useful to anonymous users.
- we could add the Light/Dark mode switch there as well

Take inspiration from https://hunger.openfoodfacts.org/settings ?

### Todo

- [ ] make the settings page accessible for all users
- [ ] make it accessible from the side drawer (remove from top right + user card)
- [ ] move light/dark mode switch to this settings page

### Related issues

- #274
