### ISSUE TITLE
Location: manage online stores

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#965]
### What

The backend now allows to create ONLINE locations, and attach proofs & prices to it (via a location_id) : https://github.com/openfoodfacts/open-prices/issues/317

Build the frontend integration

### Todo

- [x] Location selector (Price add)
  - make tabs to toggle between OSM & Online: #1010 
  - generic LocationRecentChip : #1013
  - allow adding an online shop website : #1012
- [x] Allow adding prices to an existing proof with an ONLINE location : https://github.com/openfoodfacts/open-prices-frontend/commit/819ca45702cc10ace5e5bd754ffe30300bddaea0
- [x] Location card: better manage ONLINE display
- [x] Location list: filter by type (OSM or ONLINE)

**Comment by raphodn** [comment]
Todo frontend : 
- check that it the url format before submitting
- tabs : manage the "un-toggle" error

Todo backend : 
- manage duplicate urls (return the existing id)
- remove text after slash
- add Location.source
