### ISSUE TITLE
Proof: manage new consumption-related fields (Receipt upload form, Proof display)

### ISSUE THREAD

**Issue by raphodn** [openfoodfacts/open-prices-frontend#974]
### Story

Following new "consumption-related" fields added to the backend : https://github.com/openfoodfacts/open-prices/issues/387 & https://github.com/openfoodfacts/open-prices/issues/499
--> manage them in the frontend

### Todo 

- [x] Proof add & edit form (receipt): optional input for `receipt_price_count` & `receipt_price_total` : #976
- [x] Price add form (receipt proof): optional input for `receipt_quantity` (default to 1)
- [x] Proof card: show these stats if owner : #977
- [x] Already added prices card: show these stats if filled: #1071

**Comment by raphodn** [comment]
some ideas on how the "Price quantity" field input could look like

![Image](https://github.com/user-attachments/assets/d88e972b-7649-4a46-b4ef-61e688157d2e)

**Comment by raphodn** [comment]
@serpico finally added the missing "quantity bought" field in https://github.com/openfoodfacts/open-prices-frontend/pull/1128. will be deployed soon.

closing this issue, but feel free to give feedback here after you've started using it !
and haven't forgotten #1090
